export const SAVE_ADDRESS = 'save_address'
export const SAVE_CATEGROYS = 'save_categroys'
export const SAVE_SHOPS = 'save_shops'
export const SAVE_USER = 'save_user'
export const SAVE_TOKEN = 'save_token'
export const LOGOUT = 'logout'
export const SAVE_SHOPDATAS = 'sava_shopdatas'